# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: Running tests
  inputs:
    command: 'test'
    projects: './tests/DependencyInjection.Autoregister.Abstraction.Tests/DependencyInjection.Autoregister.Abstraction.Tests.csproj
      ./tests/DependencyInjection.Autoregister.Providers.Autofac.Tests/DependencyInjection.Autoregister.Providers.Autofac.Tests.csproj
      ./tests/DependencyInjection.Autoregister.Providers.IServiceCollection.Tests/DependencyInjection.Autoregister.Providers.IServiceCollection.Tests.csproj
      ./tests/DependencyInjection.Autoregister.Providers.Unity.Tests/DependencyInjection.Autoregister.Providers.Unity.Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: './src/DependencyInjection.Autoregister/DependencyInjection.Autoregister.Abstraction.csproj'
